- name: Install Developer Packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - g++
    - gfortran
    - intltool
    - libgee-0.8-dev
    - libgtk-3-dev
    - libjson-glib-dev
    - libkeybinder-3.0-dev
    - libmysqlclient-dev
    - libncurses5-dev
    - libnotify-dev
    - libtool
    - libzeitgeist-2.0-dev
    - python-dbg
    - python-dev
    - python3-dev
    - ruby-dev
    - valac
