apt_repos:
  - 'deb http://ppa.launchpad.net/mercurial-ppa/releases/ubuntu trusty main'
  - 'ppa:fkrull/deadsnakes'
  - 'ppa:hansjorg/rust'
  - 'ppa:git-core/ppa'

apt_keys:
  - {keyserver: keyserver.ubuntu.com, id: 41BD8711B1F0EC2B0D85B91CF59CE3A8323293EE}  # Mercurial

apt_packages:
  - at
  - autoconf
  - axel
  - bzr
  - bzr-builder
  - cabal-debian
  - cabal-install
  - cmatrix
  - colordiff
  - cowsay
  - curl
  - dict
  - dict-gcide
  - dictd
  - exuberant-ctags
  - ffmpeg
  - figlet
  - git
  - htop
  - iftop
  - jq
  - lame
  - libblas3
  - liblapack3
  - lnav
  - lolcat
  - mercurial
  - mesa-utils
  - most
  - mysql-server-5.6
  - nfs-kernel-server
  - nmap
  - pass
  - python-setuptools
  - python-software-properties
  - python-sqlparse
  - shellcheck
  - subversion
  - tig
  - tree
  - unrar
  - vim
  - virtualenvwrapper
  - vorbis-tools
  - w3m
  - whois
  - xsel
  - zsh
